const COLORS=[{name:"Rood",hex:"#d93025"},{name:"Blauw",hex:"#1a73e8"},{name:"Geel",hex:"#fbbc04"},{name:"Oranje",hex:"#f28c28"},{name:"Groen",hex:"#188038"},{name:"Paars",hex:"#9334e6"},{name:"Roze",hex:"#d01884"},{name:"Turquoise",hex:"#129eaf"}];
const $=id=>document.getElementById(id);let currentRounds=[];
$("makeRounds").addEventListener("click",createRounds);$("generateAll").addEventListener("click",generateAllPDFs);$("saveConfig").addEventListener("click",downloadConfig);

function createRounds(){const count=Number($("roundCount").value),cardCount=Number($("cardCount").value);if(!Number.isInteger(count)||count<1||count>8)return showError("Aantal rondes moet 1 t/m 8 zijn.");if(!Number.isInteger(cardCount)||cardCount<1||cardCount>500)return showError("Aantal kaarten moet 1 t/m 500 zijn.");currentRounds=Array.from({length:count},(_,i)=>({id:i+1,name:`Ronde ${i+1}`,color:COLORS[i].name,hex:COLORS[i].hex,songs:[]}));renderRounds(cardCount);$("roundsSection").classList.remove("hidden");$("status").textContent=`${count} ronde(s) aangemaakt. Iedere ronde heeft minimaal 60 nummers nodig.`}
function renderRounds(cardCount){$("rounds").innerHTML=currentRounds.map((r,i)=>`<div class="round" style="--round-color:${r.hex}" data-round="${i}"><div class="round-head"><div><h3>${escapeHtml(r.name)} – ${escapeHtml(r.color)}</h3><div class="songmeta">Minimaal 60 nummers · ${cardCount} unieke kaarten · één A4 per kaart</div></div><span class="badge">${escapeHtml(r.color)}</span></div><label>Naam van de ronde<input class="round-name" value="${escapeAttr(r.name)}"></label><div class="fileline"><label>Songlijst<input class="songfile" type="file" accept=".txt,.csv,.tsv"><span class="small">TXT/CSV: één nummer per regel. CSV mag: artiest,titel.</span></label><button class="secondary paste-btn" type="button">Tekst plakken</button></div><textarea class="songs" placeholder="Artiest - Titel\nArtiest - Titel\n..."></textarea><div class="small count">0 nummers geladen</div></div>`).join("");
document.querySelectorAll(".round").forEach(el=>{const ta=el.querySelector(".songs"),file=el.querySelector(".songfile"),countEl=el.querySelector(".count"),update=()=>{const n=parseSongs(ta.value).length;countEl.textContent=`${n} nummers geladen${n<60?" – minimaal 60 nodig":""}`};ta.addEventListener("input",update);file.addEventListener("change",async()=>{if(file.files?.[0]){ta.value=await file.files[0].text();update()}});el.querySelector(".paste-btn").addEventListener("click",async()=>{try{const t=await navigator.clipboard.readText();if(t){ta.value=t;update()}}catch{alert("Plakken via de browser is geblokkeerd. Plak de lijst rechtstreeks in het tekstvak.")}})})}
function collectRounds(){return[...document.querySelectorAll(".round")].map((el,i)=>({id:i+1,name:el.querySelector(".round-name").value.trim()||`Ronde ${i+1}`,color:currentRounds[i].color,hex:currentRounds[i].hex,songs:parseSongs(el.querySelector(".songs").value)}))}
function parseSongs(text){const out=[],seen=new Set();for(const line of text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)){let artist="",title=line,p=line.split(/\t|;/);if(p.length>=2){artist=p[0].trim();title=p.slice(1).join(" - ").trim()}else{const d=line.indexOf(" - ");if(d>0){artist=line.slice(0,d).trim();title=line.slice(d+3).trim()}}const key=`${artist}|${title}`.toLowerCase();if(!seen.has(key)){seen.add(key);out.push({artist,title,key})}}return out}
async function generateAllPDFs(){const rounds=collectRounds(),count=Number($("cardCount").value),bad=rounds.filter(r=>r.songs.length<60);if(bad.length)return showError(bad.map(r=>`${r.color}: ${r.songs.length} nummers; minimaal 60 nodig.`).join("\n"));if(!window.jspdf?.jsPDF)return showError("De PDF-bibliotheek is niet geladen. Ververs de pagina met Ctrl+F5 en probeer opnieuw.");$("generateAll").disabled=true;$("status").className="status";try{for(const r of rounds){$("status").textContent=`PDF voor ${r.name} wordt gemaakt…`;await makePDF(r,makeUniqueCards(r.songs,count));await wait(100)}$("status").className="status ok";$("status").textContent=`Klaar. ${rounds.length} PDF's zijn gegenereerd met ${count} unieke kaarten per ronde.`}catch(e){console.error(e);showError("Er ging iets mis bij het maken van de PDF's: "+e.message)}finally{$("generateAll").disabled=false}}
function makeUniqueCards(songs,count){const result=[],set=new Set();let tries=0;while(result.length<count&&tries++<Math.max(10000,count*200)){const a=sampleUnique(songs,24);shuffle(a);const sig=a.map(s=>s.key).join("||");if(!set.has(sig)){set.add(sig);result.push(a)}}if(result.length!==count)throw Error(`Kon niet ${count} unieke kaarten maken.`);return result}
function sampleUnique(a,n){const c=[...a];shuffle(c);return c.slice(0,n)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
async function makePDF(round,cards){if(!window.jspdf?.jsPDF)throw Error("PDF-bibliotheek is niet geladen.");const doc=new window.jspdf.jsPDF({orientation:"portrait",unit:"mm",format:"a4"});for(let i=0;i<cards.length;i++){if(i)doc.addPage();drawCard(doc,round,cards[i],i+1,cards.length);if(i%10===0)await wait(0)}doc.save(`Muziekbingo_${$("year").value}_${round.color}.pdf`)}
function drawCard(doc,round,songs,number,total){const W=210,m=12,c=hexToRgb(round.hex);doc.setFillColor(...c);doc.rect(0,0,W,34,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(24);doc.text("MUZIEKBINGO",W/2,15,{align:"center"});doc.setFontSize(13);doc.text(`${$("year").value} · ${round.name.toUpperCase()}`,W/2,25,{align:"center"});const gx=m,gy=52,gw=W-m*2,gh=205,cw=gw/5,ch=gh/5;doc.setDrawColor(35,35,35);doc.setLineWidth(.5);let k=0;for(let row=0;row<5;row++)for(let col=0;col<5;col++){const x=gx+col*cw,y=gy+row*ch;if(row===2&&col===2){doc.setFillColor(...c);doc.rect(x,y,cw,ch,"FD");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text("VRIJ",x+cw/2,y+ch/2+4,{align:"center"})}else{doc.setFillColor(255,255,255);doc.rect(x,y,cw,ch,"FD");doc.setTextColor(20,20,20);drawSongToFit(doc,songs[k++],x,y,cw,ch)}}doc.setTextColor(70,70,70);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text(`Kaart ${String(number).padStart(3,"0")} · ${total} kaarten`,W/2,270,{align:"center"});doc.setFontSize(8);doc.text("HV Novitas · Muziekbingo",W/2,282,{align:"center"})}
function drawSongToFit(doc,song,x,y,w,h){const maxW=w-6.4,maxH=h-6.4,artist=(song.artist||"").trim(),title=(song.title||"").trim();let fs=9,best=null;while(fs>=5.7){const a=wrap(doc,artist,maxW,fs,"bold"),t=wrap(doc,title,maxW,fs,"normal"),gap=artist&&title?1.5:0,ah=fs*.48,th=fs*.46,total=a.length*ah+gap+t.length*th;if(total<=maxH&&a.length+t.length<=8){best={fs,a,t,gap,ah,th,total};break}fs-=.25}if(!best){fs=5.7;const a=wrap(doc,artist,maxW,fs,"bold").slice(0,4),t=wrap(doc,title,maxW,fs,"normal").slice(0,4);best={fs,a,t,gap:artist&&title?1:0,ah:fs*.48,th:fs*.46};best.total=best.a.length*best.ah+best.gap+best.t.length*best.th}let cy=y+(h-best.total)/2+best.fs*.36;doc.setFontSize(best.fs);if(best.a.length){doc.setFont("helvetica","bold");for(const line of best.a){doc.text(line,x+w/2,cy,{align:"center"});cy+=best.ah}}if(best.t.length){cy+=best.gap;doc.setFont("helvetica","normal");for(const line of best.t){doc.text(line,x+w/2,cy,{align:"center"});cy+=best.th}}}
function wrap(doc,text,maxWidth,fs,weight){if(!text)return[];doc.setFont("helvetica",weight);doc.setFontSize(fs);const lines=[],words=text.split(/\s+/).filter(Boolean);let line="";for(const word of words){const cand=line?`${line} ${word}`:word;if(doc.getTextWidth(cand)<=maxWidth){line=cand;continue}if(line){lines.push(line);line=""}if(doc.getTextWidth(word)>maxWidth){let part="";for(const ch of word){if(doc.getTextWidth(part+ch)<=maxWidth)part+=ch;else{if(part)lines.push(part);part=ch}}line=part}else line=word}if(line)lines.push(line);return lines}
function hexToRgb(h){h=h.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}
function downloadConfig(){const rounds=collectRounds(),year=Number($("year").value),cardCount=Number($("cardCount").value);if(rounds.some(r=>r.songs.length<60))return showError("Opslaan kan pas wanneer iedere ronde minimaal 60 nummers bevat.");const cfg={year,cardCount,rounds:rounds.map(r=>({id:r.id,name:r.name,color:r.color,songs:r.songs.map(s=>({artist:s.artist,title:s.title}))}))};const u=URL.createObjectURL(new Blob([JSON.stringify(cfg,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download=`Muziekbingo_${year}_instellingen.json`;a.click();URL.revokeObjectURL(u)}
function showError(m){$("status").className="status error";$("status").textContent=m;$("roundsSection").classList.remove("hidden")}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,"&#96;")}
